### ISSUE TITLE
afFieldValueIs not working when form initially loads

### ISSUE THREAD

**Issue by mbabauer** [aldeed/meteor-autoform#1221]
In my Autoform, I need to show/hide a section of date pickers based on the state of a dropdown:

```javascript
<div class="form-group col-md-6">
	<label>Assignment State</label>
	{{> afFieldInput name="state" id="state" disabled="disabled"}}
</div>
{{#if afFieldValueIs name="state" value="Approved"}}
	<div class="col-md-6">
		<div class="form-group">
			<label for="scheduledAt">Scheduled Date/Time</label>
			{{> afFieldInput name="scheduledAt" id="scheduledAt" disabled="disabled"}}
		</div>
		<div class="form-group">
			<label for="estimatedCompletion">Estimated Completion</label>
			{{> afFieldInput name="estimatedCompletion" id="estimatedCompletion" disabled="disabled"}}
		</div>
	</div>
{{/if}}
```

The form is loaded by selecting the value in a Bootstrap list group.  The user selects a value on the left, which sets a `Session` value that triggers the load of the form, in read-only mode, on the right.

However, upon initial run, the `if` test on `template.view._domrange` fails in the following code (lines 422-426) because the value of `template.view._domrange` at that point is `false`:
```javascript
/**                                                                                                                    // 392
 * @method AutoForm.getFieldValue                                                                                      // 393
 * @public                                                                                                             // 394
 * @param {String} fieldName The name of the field for which you want the current value.                               // 395
 * @param {String} [formId] The `id` attribute of the `autoForm` you want current values for. Default is the closest form from the current context.
 * @return {Any|undefined}                                                                                             // 397
 *                                                                                                                     // 398
 * Returns the value of the field (the value that would be used if the form were submitted right now).                 // 399
 * This is a reactive method that will rerun whenever the current value of the requested field changes. Return value will be undefined if the field is not currently rendered.
 */                                                                                                                    // 401
AutoForm.getFieldValue = function autoFormGetFieldValue(fieldName, formId) {                                           // 402
  // find AutoForm template                                                                                            // 403
  var template = Tracker.nonreactive(function () {                                                                     // 404
    return AutoForm.templateInstanceForForm(formId);                                                                   // 405
  });                                                                                                                  // 406
                                                                                                                       // 407
  if (!template) {                                                                                                     // 408
    if (formId) {                                                                                                      // 409
      AutoForm.rerunWhenFormRenderedOrDestroyed(formId);                                                               // 410
    }                                                                                                                  // 411
    return;                                                                                                            // 412
  }                                                                                                                    // 413
                                                                                                                       // 414
  // reactive dependency                                                                                               // 415
  template.formValues = template.formValues || {};                                                                     // 416
  if (!template.formValues[fieldName]) {                                                                               // 417
    template.formValues[fieldName] = new Tracker.Dependency();                                                         // 418
  }                                                                                                                    // 419
  template.formValues[fieldName].depend();                                                                             // 420
                                                                                                                       // 421
  if (!template.view ||                                                                                                // 422
      !template.view._domrange ||                                                                                      // 423
      template.view.isDestroyed) {                                                                                     // 424
    return;                                                                                                            // 425
  }                                                                                                                    // 426
                                                                                                                       // 427
  var doc = AutoForm.getFormValues(formId, template, null, false);                                                     // 428
  if (!doc) {                                                                                                          // 429
    return;                                                                                                            // 430
  }                                                                                                                    // 431
                                                                                                                       // 432
  var mDoc = new MongoObject(doc);                                                                                     // 433
  var value = mDoc.getValueForKey(fieldName);                                                                          // 434
                                                                                                                       // 435
  return value;                                                                                                        // 436
};     
```

As a result, the afFieldValueIs is not evaluated, and my dynamically shown fields are not show, despite the value for `state` being `"Approved"`.

How can I trigger my fields to be properly rendered based on the `state` value?

**Comment by abernix** [comment]
Probably related to #1163

**Comment by abernix** [comment]
I would try making your own helper:

```js
Template.TEMPLATE_NAME.helpers({
  stateIsApproved: function () {
    var formId = AutoForm.getFormId();
    return AutoForm.getFieldValue("state", formId) === "Approved";
  }
});
```

```html
{{#if stateIsApproved}}
  <blah></blah>
{{/if}}
```

**Comment by abernix** [comment]
Alternatively, and pretty much just for fun, if you want to see if it's actually the same bug, force your autoform to 5.4.0 (if you don't have other dependencies that prevent it – which you might):

`meteor add aldeed:autoform@=5.4.0`

**Comment by mbabauer** [comment]
I just updated everything to Meteor 1.2, and it pulled in autoform 5.5.1, and still the same issue.  Admittedly it does sound similar, but in my case it is consistently when the value is checked on the initial render.  If I "edit" the page and change the value, it works from that point...until I select a different item from the left, which does another initial template render on the right.

I didn't think about doing my own helper.  I guess what I will need to do is test if the page is rendered, and if so, grab the value of the select, and if not use the one from the DB.

**Comment by abernix** [comment]
I think you can literally just replace the `{{#if afFieldValueIs name="state" value="Approved"}}` line with `{{#if stateIsApproved}}` as I suggested, no extra work necessary.

Internally, it calls the `AutoForm.getFieldValue` API just the same, but I believe the problem is that `formId` is not set on the initial render, and I think fixed by the #1195 pull request.

**Comment by mbabauer** [comment]
Cool.  I'll subscribe to the PR.  Hopefully it's not too long before they get it into the 5.5 branch.  Thanks!

**Comment by thebarty** [comment]
Hi guys,

I ran into the same problem and opened a 2 issues.

1) I have problems with using ``AutoForm.getFieldValue`` in a helper:
https://github.com/aldeed/meteor-autoform/issues/1251

2) and with initial data ``afFieldValueIs`` https://github.com/aldeed/meteor-autoform/issues/1250.

**Did you guys find a solution for this?**

**Comment by tcastelli** [comment]
+1 Couldn't get it to work correctly, I have created a new helper to check if the value from schema exists and otherwise use autoform.getfieldValue() but still doesn't get the values after updating the document values

**Comment by weeger** [comment]
+1

**Comment by weeger** [comment]
Package update solved

**Comment by tcastelli** [comment]
update to what version? as far as I can see the latests is still 5.7.1 (and it's not working there)

**Comment by weeger** [comment]
Maybe I had not exactly the same problem sorry, it was realted with the "afFieldValueIs" initial update, solved into : https://github.com/aldeed/meteor-autoform/issues/1163
