### ISSUE TITLE
Autoform + i18n?

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-autoform#483]
It would be very nice to have a built-in integration with a package such as @theosp's [tap:i1n8](https://github.com/TAPevents/tap-i18n).

For example, maybe if an `i18n` option is set, Autoform could get the label via tap:i18n using the field name as key, instead of via the *label* option?

**Comment by johynpapin** [comment]
Hello !
My option, for the moment, is :
```javascript
Books.attachSchema(new SimpleSchema({
  title: {
    type: String,
    label: function() {
      if(Meteor.isClient) {
        return(TAPi18n.__('labels.title'));
      }else{
        return('title');
      }
    },
    max: 200
}));
```
The label part can't be placed inline... And the i18n can work on the server. ;)

**Comment by SachaG** [comment]
I found a cleaner way to do i18n. Just before attaching the schema, I do this:

```js
_.each(postSchemaObject, function (property, key) {
  if (!property.label) {
    postSchemaObject[key].label = function () {
      return i18n.t(key)
    };
  }
});
```

I go over each schema property. If it doesn't already have a label, I set the `label` to a function that returns an i18n string based on the property name (`key`). 

Oh, and I use a function instead of setting the label directly to make sure it's evaluated later on once the i18n stuff is already defined. 

I can then go on and define and attach the schema as usual:

```js
Posts = new Meteor.Collection("posts");

postSchema = new SimpleSchema(postSchemaObject);

Posts.attachSchema(postSchema);
```

**Comment by aldeed** [comment]
@SachaG any ideas how we could make it more "built in" without committing to any one i18n library/solution?

I'm thinking maybe:

```js
SimpleSchema.defaultLabel = function (key) {
  return i18n.t(key);
};
```

SS would simply check whether `SimpleSchema.defaultLabel` is set to a function and use that as fallback before resorting to humanizing the key string.

**Comment by SachaG** [comment]
That sounds perfect :)

**Comment by SachaG** [comment]
Just to give more info about my use case: I want each field to have an i18n string based on its name. But if no string is defined, the label should fall back to humanizing the key. 

Additionally, if a label *is* explicitly defined (for example someone is customizing Telescope and just wants to overwrite a single label, not i18n'ize the whole thing), then it should just use that. 

So I think your solution covers it pretty well. In order of priority, it would use:

- The `label` property.
- The result of `defaultlabel(key)`.
- The result of `humanize(key)`.

**Comment by abernix** [comment]
This sounds like a suitable solution for me as well.

**Comment by gwendall** [comment]
Started writing i18n error messages, feel free to contribute! https://github.com/gwendall/meteor-autoform-i18n

**Comment by aldeed** [comment]
Moved this issue to simple schema repo: https://github.com/aldeed/meteor-simple-schema/issues/343

**Comment by gwendall** [comment]
FYI, I also published a package for this purpose. https://github.com/gwendall/meteor-autoform-i18n

**Comment by aldeed** [comment]
Yeah @gwendall, thanks. I looked briefly at it the other day and it seemed like a good solution. My goal is just to make any core changes to better enable packages like yours, so if you have any suggestions let me know.

**Comment by almogdesign** [comment]
I'm using @gadicc meter messageformat which is working great and very simple to implement IE|:

title: {
        type: String,
        label: mf('title', 'Title'),
        max: 200
    },

but it's not reactive I wounding if there is a way to rerun the Schema so it reloads if a language is changed?

**Comment by MarcTe** [comment]
I am still not competent enough for understanding all what was said in the thread,
but here is my POV: 1) a web app needs to language scalability from day 1 (this means everithing displayed). 

2) Not sure how similar it is with i18n method, but my idea was to assign, athe the router, a different language specific collection to the same "label" collection variable name. It would be reactive with its subscription. Then some reactive code would load reactive objects with its content. So, the name=attribute, should be able to trigger the lookup in the object.

3) A final (dream come true) would be the possibility to "fit-in" the label content to the surrounding container, so if the translated text is longer, it woud either wrap lines or further reduce font size.
Bottom of the line: having only one template for all languages.

Thanks for your hidden work!
Marc

**Comment by tcastelli** [comment]
after updating to 5.7.1, the previous trick to implement language switch is no longer working, any idea of what happened? (Reverting to 5.4.0 makes it work again)
````javascrip
getLabelsFor = (schema, name, sessionLanguage) ->
  labels = {}
  for fieldName in schema._schemaKeys
    i18n_key = name.charAt(0).toLowerCase() + name.slice(1) + "." + fieldName.split(".$").join("")
    # console.log "schema:  " + name + "  fieldName:  " + fieldName + " i18nkey: " + i18n_key
    translation = i18n.t(i18n_key)
    if new RegExp('string').test(translation) isnt true and translation isnt i18n_key
      # schema._schema[fieldName].label =  i18n.t(i18n_key)
      labels[fieldName] = translation
  return labels
````
