### ISSUE TITLE
Upgraded from 5.1.2 to 5.2.0 now getting errors.

### ISSUE THREAD

**Issue by instaalexgomez** [aldeed/meteor-autoform#961]
Getting this error multiple times after upgrading:
```
autoform-inputs.js:186 Uncaught TypeError: Cannot read property 'changed' of undefined
```

```
function markChanged() {
    // We always want to be sure to wait for DOM updates to
    // finish before we indicate that values have changed.
    // Using a value of 0 here did not work, but 100 seems to
    // work in testing. We'll need to keep an eye on this.
    // Not an ideal solution.
    setTimeout(function () {
      // Template or view may have disappeared while
      // we waited to run this
      if (template &&
          template.view &&
          template.view._domrange &&
          !template.view.isDestroyed) {

        template.formValues[fieldName].changed();
        template.formValues[fieldName].requestInProgress = false;

      }
    }, 100);
  }
```

Thoughts?

**Comment by roelvan** [comment]
I have the same problem.

**Comment by ribbedcrown** [comment]
Me too.

**Comment by castlefields** [comment]
Same here - Seems though that the issue is within the .Meteor folder somewhere as I have replaced this with another .Meteor folder from another project and the error goes away. With this in mind I then copied the versions and packages back into my original folder ensuring all of the config was the same - The Error remained. Therefore it seems the issue is deeper somewhere...

**Comment by trisager** [comment]
Error occurs with nested objects here too.

**Comment by miri-am** [comment]
+1

**Comment by theduke** [comment]
+1

**Comment by marktomm** [comment]
+1

**Comment by sturoid** [comment]
+1

**Comment by cskaandorp** [comment]
+ 1. 

I just downgraded to 4.2.2 because of the bug-ridden 5.1.2 did not function properly. Then came 5.2.0, I thought I was saved, upgraded my app and BAM! Another bug. So know I am contemplating on downgrading yet again. Great. This is rather frustrating. None of the pull requests are processed, almost nothing is happening.

Sorry about that. But this package turns my hair grey.

Anybody knows how to get over this bug?

**Comment by macsj200** [comment]
+1

**Comment by lyckron** [comment]
+1

**Comment by shkomg** [comment]
+1

**Comment by flean** [comment]
+1

**Comment by nate-strauser** [comment]
+1

**Comment by kevohagan** [comment]
+1 on this

**Comment by jadsonlourenco** [comment]
+1

**Comment by dominikzborowski** [comment]
+1

**Comment by jotakaele** [comment]
+1

**Comment by movila** [comment]
+1

**Comment by discdiver** [comment]
+1

**Comment by fabienb4** [comment]
When using array fields, [this part (L197 to L202)](https://github.com/aldeed/meteor-autoform/blob/master/autoform-inputs.js#L200) of the code never actually does anything because `template.formValues[fieldName]` in `markChanged()` is never defined.

At first `fieldName` is equal to `xxx.$.yyy`, but when entering this loop, it becomes `xxx.$` then `xxx` both of which aren't in `template.formValues`. Plus there is a race condition with the setTimeout, `fieldName` ends up always being `xxx` when timeouts finish.

5.2.0 removed this part of code from markChanged():
```js
    if (!template.formValues[fieldName]) {
      template.formValues[fieldName] = new Tracker.Dependency();
    }
```
It was creating a new `Tracker.Dependency` when `fieldName` was equal to `xxx.$` and `xxx`, now it is not.

**Comment by aldeed** [comment]
Sorry about this bug, and thanks for your patience. Fixed in 5.3.0, just released.

**Comment by sturoid** [comment]
Thanks a ton Eric. This package is glorious.

**Comment by fabienb4** [comment]
Thanks!

I just updated semantic-ui theme to use 5.3.0, I think many will appreciate the fixes from 5.2.0 & 5.3.0!

**Comment by jlourenco** [comment]
Just updated to 5.3.0 and still get the same error when using nested fields. Anyone else?

**Comment by kevohagan** [comment]
same here

**Comment by aldeed** [comment]
@jlourenco @kevohagan can one of you submit a new issue with a small reproduction? I did not see this error anymore in the demo app with 5.3.0. Maybe it is similar but different.

**Comment by fabienb4** [comment]
No errors here neither.
Maybe a package dependency keeping autoform to a lower version.

Check `.meteor/versions` file for autoform version.

**Comment by shkomg** [comment]
all is working great, can't see any errors anymore

2015-05-29 17:53 GMT+03:00 Fabien Blanchard <notifications@github.com>:

> No errors here neither.
> Maybe a package dependency keeping autoform to a lower version.
>
> Check .meteor/versions file for autoform version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aldeed/meteor-autoform/issues/961#issuecomment-106837613>
> .
>



-- 
Best regards

Serhiy Khvashchuk

**Comment by jlourenco** [comment]
Thanks @fabienb4, you were right about the package dependency. After a "forced" update everything worked as mentioned.

Thanks @aldeed for the great work.

**Comment by kevohagan** [comment]
my bad too!

**Comment by avishekgurung** [comment]
I got the same error even after updating...
I did meteor update aldeed:autoform,
Now when i see the version file, the autoform has been update to 5.2*. Wondering why it is not getting updated to 5.3

**Comment by fabienb4** [comment]
A package in your app is using a lower version of autoform, Meteor isn't updating it to avoid breaking changes. You can figure out which package by looking in the `package.js` files of each package.

Look for a line like this one:
```js
  api.use('aldeed:autoform@5.2.0', 'client');
```

**Comment by avishekgurung** [comment]
I could not find this line ... I am using linux, I even searched with grep like this sudo grep -r "api.use('aldeed:autoform@5.2.0', 'client');" * .*   But still could not find any such packages. And yes, I am using many packages. So is there any alternate fix for it, I mean can I force update to 5.3, if so, how can I do it?

**Comment by avishekgurung** [comment]
Is there any workaround for this, so far, could not find any dependent package.

**Comment by shkomg** [comment]
try ```meteor add aldeed:autoform@5.3.0```

2015-06-01 12:16 GMT+03:00 Avishek Gurung <notifications@github.com>:

> Is there any workaround for this, so far, could not find any dependent
> package.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aldeed/meteor-autoform/issues/961#issuecomment-107377750>
> .
>



-- 
Best regards

Serhiy Khvashchuk

**Comment by fabienb4** [comment]
@avishekgurung The line could be a little different, if the package author use a variable for 'client'...
You can also try using a specific version when adding the package:
```js
meteor add aldeed:autoform@=5.3.0
```

For anyone having the same problem:
Based on autoform's readme packages list, here are the packages using a specific version of autoform after 5.0.0:

`5.1.2`:
- drewy:autoform-datetimepicker
- mpowaga:autoform-summernote
- yogiben:autoform-map
- yogiben:autoform-file
- yogiben:admin
- planifica:wizard
- yogiben:autoform-modals
- orionjs:core

`5.1.1`:
- gildaspk:autoform-materialize

`5.0.2`:
- miguelalarcos:afwrap-xautocomplete

If you are using any of these packages, you won't be able to update to 5.3.0 until the packages has been updated.
